"""Write docs/PARAMETERS.md: every variable a batch spec can set, every maneuver and every exportable
signal, generated from the same catalog the engine validates against (so it cannot go stale).

    python scripts/make_param_reference.py          # rewrite the file
    python scripts/make_param_reference.py --check  # exit 1 if the file is out of date (used by the tests)
"""
from __future__ import annotations

import sys
from pathlib import Path

from rc_drift_sim.datagen.catalog import build_catalog
from rc_drift_sim.datagen.spec import DISTS

OUT = Path(__file__).resolve().parents[1] / "docs" / "PARAMETERS.md"


def _fmt(v) -> str:
    if v is None:
        return "auto"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float):
        return f"{v:.6g}"
    return str(v)


def render() -> str:
    cat = build_catalog()
    L = ["# Parameter reference", "",
         "Every variable a batch spec can set (see [DATA_GENERATION.md](DATA_GENERATION.md) for the spec format).",
         "Defaults come from `rc_drift_sim/configs/*.yaml`. **Basic** variables are the ones most worth",
         "changing; **advanced** ones are numerical or fine-tuning settings. *Structural* settings split a",
         "batch into separate vectorized groups when they vary.", "",
         "This file is generated by `python scripts/make_param_reference.py`; do not edit it by hand.", ""]
    L += ["## Contents", ""] + [f"- [{g['label']}](#{g['id']})" for g in cat["groups"]] + \
         ["- [Maneuvers (input generators)](#maneuvers)", "- [Exportable signals](#signals)",
          "- [Distributions](#distributions)", ""]
    for g in cat["groups"]:
        L += [f'<a id="{g["id"]}"></a>', f"## {g['label']}", ""]
        if "choice_key" in g:
            L += [f"`{g['choice_key']}` selects the {g['label'].lower()}: " +
                  ", ".join(f"`{c}`" for c in g["choices"]) + f" (default `{g['default_choice']}`).",
                  "The defaults below are those of the default choice; each choice has its own values in the YAML file.", ""]
        L += ["| key | default | unit | level | description |", "|---|---|---|---|---|"]
        for level in ("basic", "advanced"):
            for r in g["fields"]:
                if r.get("level", "advanced") != level:
                    continue
                extra = []
                if r.get("structural"):
                    extra.append("*structural*")
                if r.get("choices"):
                    extra.append("one of " + ", ".join(f"`{c}`" for c in r["choices"]))
                if r.get("per_wheel"):
                    extra.append("`per_wheel` allowed")
                desc = r["desc"] + ("; " + "; ".join(extra) if extra else "")
                L.append(f"| `{r['key']}` | {_fmt(r['default'])} | {r['unit'] or '-'} | {level} | {desc} |")
        L.append("")
    L += ['<a id="maneuvers"></a>', "## Maneuvers (input generators)", "",
          "Set with `\"maneuver\": {\"type\": ..., \"params\": {...}}`; every parameter accepts a distribution.", ""]
    for name, m in cat["maneuvers"].items():
        L += [f"### `{name}`: {m['label']}", "", m["desc"], "", "| parameter | default | unit | description |",
              "|---|---|---|---|"]
        L += [f"| `{p['name']}` | {_fmt(p['default'])} | {p['unit']} | {p['desc']} |" for p in m["params"]]
        L.append("")
    L += ['<a id="signals"></a>', "## Exportable signals", "",
          "Choose groups in `export.signals`; groups marked default are selected in `default_spec()`.",
          "Per-wheel signals have four columns in wheel order FL, FR, RL, RR.", "",
          "| group | signal | unit | per wheel | description |", "|---|---|---|---|---|"]
    for g in cat["signals"]:
        for s in g["signals"]:
            L.append(f"| `{g['key']}`{' (default)' if g['default'] else ''} | `{s['name']}` | {s['unit']} | "
                     f"{'yes' if s['per_wheel'] else ''} | {s['desc']} |")
    L += ["", '<a id="distributions"></a>', "## Distributions", "", "| dist | fields |", "|---|---|"]
    L += [f"| `{k}` | {', '.join(f'`{f}`' for f in v)} |" for k, v in DISTS.items()]
    L += ["", "Options: `\"mode\": \"scale\"` multiplies the default instead of replacing it; `\"per_wheel\": true`",
          "(condition.* only) draws each wheel separately; `normal` accepts optional `low`/`high` clipping;",
          "`choice` accepts optional `weights`.", ""]
    return "\n".join(L)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text() == text
        print("docs/PARAMETERS.md is up to date" if ok else "docs/PARAMETERS.md is out of date: run scripts/make_param_reference.py")
        return 0 if ok else 1
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
